File changes - Unable to fix  commitID and Message
ucsb-cs156-s24/proj-organic-s24-5pm-4 pull request #10
Opened 2024-05-19 06:31 UTC by ElijahCanderson

2024-05-20 20:13 UTC, pconrad requested changes
I see some things that might help get this working.

You also need to check what's in the properties files... I'll come back and add more comments if I find anything there that needs to be changed.

2024-05-20 20:13 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/services/SystemInfoServiceImpl.java
> +    .githubUrl(githubUrl("https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4", this.commitId))
```suggestion
    .githubUrl(githubUrl( this.sourceRepo, this.commitId))
```
Again, no hard coding.

2024-05-20 20:13 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/organic/services/SystemInfoServiceImplTests.java
> +    assertEquals("https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4", si.getSourceRepo());
```suggestion
       assertEquals("https://github.com/ucsb-cs156/proj-organic", si.getSourceRepo());
```

The default value should be `https://github.com/ucsb-cs156/proj-organic"` in the properties files, and you should be able to override it by setting SOURCE_REPO.

2024-05-20 20:15 UTC, pconrad commented
The property file value is exactly as it should be:
```
app.sourceRepo=${SOURCE_REPO:${$env.SOURCE_REPO:https://github.com/ucsb-cs156/proj-organic}}
```

Leave that as the default value, and only override it to `ttps://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/` by setting SOURCE_REPO in either .env or on your dokku instance.

Also, don't forget to do:
```
dokku git:set appname keep-git-dir true
```

on the dokku apps where you run this.  Not needed on localhost since you are running `mvn spring-boot:run` in the directory that has the .git subdirectory already.

2024-05-22 00:17 UTC, ElijahCanderson commented
I have already tested without hard coding, and it does not work. The url in the api/system info will not change locally and commit id and message are stuck on unkown.

My implementation in my .env is SOURCE_REPO=https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4
But that does not change the URL. I would think this is the issue for the Commit ID and Commit message not working, but configuring it on dokku does change the URL (without hardcoding), yet CommitID and Commit message remain unkown. The only way I have found that the Url changes locally is with hardcoding.
Even if I change it in the properties file, IE, setting my teams repo as the default one, the url remains stuck at the base organic repo locally.

I did make the changes you mentioned as a double check and the issue still persists. Are there other files I should be changing outside of the one's changed in the provided pull request? I have looked and have not found any that stand out.

2024-05-23 04:42 UTC, pconrad approved these changes
LGTM!  Thanks for your patience

2024-05-23 04:44 UTC, Division7 approved these changes, later dismissed
LGTM 😎 🤙

2024-05-23 04:48 UTC, pconrad requested changes
I know you want to be done with this, and I want you do be (and get the points)... but hear me out...

See comments below...

2024-05-23 04:48 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/services/SystemInfoServiceImpl.java
> +  private String sourceRepo = "https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4";
I do need you to change this back.   Ultimately, the code that runs the app is proj-organic.

In terms of figuring out why localhost is different, consider this line:

https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/blob/44a929d1384a0cc88591765d5ae7e340817bb517/src/main/resources/application-development.properties#L13

I'm wondering if the fact that that is there in application-development.properties but not in application-production.properties is part of why it's not working on localhost?

Maybe experiment with that?

2024-05-25 20:24 UTC, pconrad approved these changes
LGTM!

2024-05-25 20:28 UTC, merged