Jason Added Staff Index Page (Redirected from a Course's Staff Button)
ucsb-cs156-s24/proj-organic-s24-5pm-4 pull request #26
Opened 2024-05-28 21:31 UTC by jason-rodrigues

Updated Staff Table Loading:
![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/assets/97640916/850c1d7a-5228-41c8-879c-924e74696bf6)
Edit and Create Page Redirecting to Placeholders (I guessed for some of the URLs... if I should change these, lmk)
![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/assets/97640916/b8d8d207-0558-4d2e-85ae-9ca5949a3b9f)
![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/assets/97640916/f96a9218-8b2c-438d-a3b8-40d9d2a84d63)

Deployed on Dokku [here]( https://proj-organic-jason-rodrigues-dev.dokku-12.cs.ucsb.edu) 
(Staff + Team should be admin, lmk if there's any issues)

2024-05-29 00:39 UTC, ElijahCanderson approved these changes, later dismissed
LGTM

2024-05-30 20:53 UTC, pconrad requested changes
Overall, code looks good!  

But we need to remove edit; there's literally nothing to edit for a staff member.  A github user is either a member of the staff for a given course, or they are not.  So it's just add or delete; nothing else.

2024-05-30 20:53 UTC, pconrad commented on frontend/src/App.js
> +      <Route path="/courses/:id/editStaff" element={<StaffEditPage />} />
```suggestion
```

There is no use case for a staff edit button.  It's only add and delete.

2024-05-30 20:53 UTC, pconrad commented on frontend/src/App.js
> +import StaffEditPage from "main/pages/StaffEditPage";
There is no use case for a staff edit button. It's only add and delete.

2024-05-30 20:53 UTC, pconrad commented on frontend/src/main/components/Staff/StaffTable.js
> +        columns.push(ButtonColumn("Edit", "primary", editCallback, "StaffTable"));
There is no use case for a staff edit button. It's only add and delete.
```suggestion
```

2024-05-30 20:53 UTC, pconrad commented on frontend/src/main/pages/StaffEditPage.js
> +}
Remove file: There is no use case for a staff edit button. It's only add and delete.

2024-05-30 20:53 UTC, pconrad commented on frontend/src/stories/pages/StaffEditPage.stories.js
> +
There is no use case for a staff edit button. It's only add and delete.

2024-05-30 20:53 UTC, pconrad commented on frontend/src/tests/pages/StaffEditPage.test.js
> +
There is no use case for a staff edit button. It's only add and delete.

2024-06-01 20:29 UTC, Division7 submitted a review, later dismissed
LGTM 😎 🤙

2024-06-02 17:56 UTC, pconrad approved these changes
LGTM

2024-06-02 17:56 UTC, merged