Sreeganesh schools crud edit
ucsb-cs156-s24/proj-organic-s24-5pm-4 pull request #31
Opened 2024-05-29 20:09 UTC by SR33G33

Edit Page for Admins is visible in the Schools tab when edit button is pressed

![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/assets/51520358/20cd4337-1543-4842-8211-4a13596f15f5)

allows user to edit successfully
TODO: Still allows users to edit abbrev which cause some funky stuff to happen where it overwrites another table entry if the new abbrev matches an old one

![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/assets/51520358/796ad69c-d951-4966-8bae-5787737e578a)

![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/assets/51520358/ecf07aaf-7d4d-42c8-a873-8f1fb6802ffa)

This branch is currently deployed to: https://proj-organic-sr33g33-dev.dokku-12.cs.ucsb.edu/

*Note if the deployed app looks like an old one I might just have pushed a different branch to debug, shoot me a message on slack and I can deploy the correct branch

2024-05-29 20:35 UTC, jason-rodrigues reviewed
![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/assets/97640916/e080f4a6-e751-41e5-a7bd-a265545df47e)
![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/assets/97640916/e9f29e5b-7d19-4ad7-b428-afe90d9f3c87)
Term RegEx doesn't seem to be enforced on update

2024-05-29 22:36 UTC, SR33G33 commented
These are kind of backend issues, Ill make a new PR to fix these after this one is merged

TODO: Make the update check that the termDescription matches new TermRegex
TODO: Make sure abbrev cant be edited in update

2024-05-30 00:12 UTC, ElijahCanderson submitted a review, later dismissed
LGTM

2024-06-01 00:16 UTC, pconrad commented
The create school button leads to an error message for me on the dokku deployment linked in the PR.

I can't merge this unless/until I can test it.

2024-06-01 00:48 UTC, SR33G33 commented
redeployed app and seems to be working on my end, I pushed the most updated working version that has edit and delete and create functionality

note: still has the edit page bugs that I pointed out in the edit page PR which will be fixed in a different PR

2024-06-01 17:56 UTC, pconrad commented on frontend/src/tests/pages/SchoolCreatePage.test.js
> +                "termDescription": "s24",
```suggestion
                "termDescription": "quarter",
```

2024-06-01 17:57 UTC, pconrad requested changes
Let's clear up the confusion about the use case for these fields.

2024-06-05 23:01 UTC, pconrad approved these changes
LGTM

2024-06-05 23:01 UTC, merged