completed the student table
ucsb-cs156-s24/proj-organic-s24-5pm-4 pull request #39
Opened 2024-05-31 00:57 UTC by GuBinhti

Created the Table for student as well as the story and tests

close #16

2024-06-01 00:22 UTC, pconrad commented on frontend/src/tests/components/Student/StudentTable.test.js
> +// import { fireEvent, render, waitFor, screen } from "@testing-library/react";
Commented out code.

2024-06-01 00:22 UTC, pconrad commented on frontend/src/tests/components/Student/StudentTable.test.js
> +    // expect(deleteButton).toHaveClass("btn-danger");
commented out code

2024-06-01 00:22 UTC, pconrad requested changes
commented out code.  otherwise LGTM.

2024-06-02 06:42 UTC, jason-rodrigues commented
Edit: 
Expanded Student Table to match all the columns specified in the Kanban Board Item/Backend URL endpoint:
![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/assets/97640916/28078d5b-5db7-4662-b9c0-5e8ca0ed64d6)
![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-4/assets/97640916/0036fc80-bb89-43c6-9135-52a88d602609)

2024-06-02 06:54 UTC, SR33G33 approved these changes
LGTM 😎 !! I can see the table on the gh-pages storybook

2024-06-02 18:28 UTC, pconrad approved these changes
LGTM

2024-06-02 18:28 UTC, merged